<?php

namespace Modules\Registrar\Subjects\Models;

use Illuminate\Database\Eloquent\Model;

class Subjects extends Model
{
    protected $table = 'subjects';
    protected $primaryKey = 'SubjectID';
    protected $fillable = array(
        'SubjectCode',
        'SubjectTitle',
        'SubjectDesc',
        'LMSGroup',
        'AcadUnits',
        'LabUnits',
        'CreditUnits',
        'SubjectGE',
        'SubjectElective',
        'SubjectMajor',
        'SubjectComputer',
        'InclGWA',
        'Inactive',
        'LectHrs',
        'LabHrs',
        'SubjectAreaID',
        'LevelID',
        'SubjectMode',
        'MinSize',
        'MaxSize',
        'InclTFCompute',
        'InclLFCompute',
        'IsNonAcademic',
        'Alias1',
        'Alias2',
        'CollegeOwner',
        'OtherSchool',
        'ChargeAirconLecUnit',
        'ChargeAirconLabUnit',
        'OldSubjectCode',
        'OldSubjectTitle',
        'OldSubjectDescription',
        'DateLocked',
        'SubjectELearning',
        'IsTransmutedGrade',
        'SubjectWithInternet',
        'IsClubOrganization',
        'SubjParentID',
        'SubjCompPercentage',
        'CreatedBy',
        'CreatedDate',
        'ModifiedBy',
        'ModifiedDate',
        'LockedBy',
        'IsPracticum',
        'SubjGroupID',
        'ChargeAirconCreditUnit',
        'Alias3',
        'TargetHoursPerWeek',
        'TransferedSubjectID',
        'ThesisSubject',
        'ChineseSubject',
        'Weight',
        'LetterGradeOnly',
        'IsChinese',
        'ShowGradeComponents',
        'ShowPrelimColumn',
        'ShowMidtermColumn',
        'ShowFinalColumn',
        'IsSemestral',
        'IsNonConduct',
        'SuppressSubject',
        'SuppressAcademicGrade',
        'SuppressConductGrade',
        'CollegeID',
        'IsPassFail',
        'IsAcademicClass',
        'FacultyAcadUnits',
        'FacultyLabUnits',
        'ShowOnReport',
        'ConductUnit',
        'IsNstp',
        'IsRLE',
        'RLELab',
        'RLEC',
        'PolicyID',
        'concat',
    );
}