<?php

namespace Modules\Employee\Models\Employees;

use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
    protected $table = 'hr_employees';
    protected $primaryKey = 'EmployeeID';
    protected $fillable = array(
        'LastName',
        'FirstName',
        'MiddleName',
        'MiddleInitial',
        'ExtName',
        'Prefix',
        'FullName',
        'AppointDate',
        'PermanentDate',
        'BasicSalary',
        'PSICode',
        'EmpStatusID',
        'PosnTitleID',
        'AuthTitle',
        'CampusID',
        'CollegeID',
        'DeptID',
        'DateOfBirth',
        'PlaceOfBirth',
        'Gender',
        'CivilStatusID',
        'NationalityID',
        'TelNo',
        'MobileNo',
        'Email',
        'Height',
        'Weight',
        'AddressNo',
        'Street',
        'Barangay',
        'TownCity',
        'Province',
        'ZipCode',
        'GSIS',
        'SSS',
        'PAGIBIG',
        'PhilHealth',
        'TIN',
        'Father_Surname',
        'Father_Contact',
        'Father_FirstName',
        'Father_MiddleName',
        'Mother_Surname',
        'Mother_Maiden',
        'Mother_Contact',
        'Mother_MiddleName',
        'Spouse_Surname',
        'Spouse_FirstName',
        'Spouse_MiddleName',
        'Spouse_Occupation',
        'Spouse_Agency',
        'Spouse_AgencyAddress',
        'Spouse_AgencyTelNo',
        'Spouse_AnnualIncome',
        'Photo',
        'Signature',
        'Inactive',
        'Suffix',
        'LoadReleased',
        'HREmployeeID',
        'ChineseName',
        'SmartCardID',
        'Mother_FirstName',
        'Spouse_Contact',
        'Econtact_Occupation',
        'Econtact_Contact',
        'Econtact_Relationship',
        'PRC_No',
        'Profession',
        'PRC_License_No',
        'PRC_License_No_Valid_Until',
        'AdministrativeLoadDesc',
        'ReligionID',
        'Econtact_MiddleName',
        'Econtact_Surname',
        'Econtact_FirstName',
        'Father_Occupation',
        'Mother_Occupation'
    );
}